[package]
name = "parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.1"
walkdir = "2.3.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.17"
